#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m space 1 --label dev
yabai -m space 2 --label web
yabai -m space 3 --label conference
yabai -m space 4 --label tools
yabai -m space 5 --label misc

yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^AWS VPN Client$" sticky=on layer=above manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^SnippetsLab$" sticky=on layer=above manage=off
yabai -m rule --add app="^ExpressVPN$" layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" layer=above manage=off
yabai -m rule --add app="^Calculator$" sticky=on layer=above manage=off

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_opacity off
# this setting is currently broken for Monterey
# yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity 0.8
yabai -m config normal_window_opacity 0.8
yabai -m config window_border off
yabai -m config window_border_width 5
yabai -m config active_window_border_color 0xE0808080
yabai -m config normal_window_border_color 0x00010101
yabai -m config insert_feedback_color 0xE02d74da
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 60
yabai -m config bottom_padding 85
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

echo "yabai configuration loaded.."
