require("colorizer").setup({
	css = { rgb_fn = true },
	scss = { rgb_fn = true },
	sass = { rgb_fn = true },
	stylus = { rgb_fn = true },
	vim = { names = false },
	tmux = { names = true },
	"eelixir",
	"javascript",
	"javascriptreact",
	"typescript",
	"typescriptreact",
	"zsh",
	"sh",
	"conf",
	"lua",
	html = {
		mode = "foreground",
	},
})
