vim.g.mapleader = " "
vim.g.maplocalleader = " "

require "core.mason_path"
require "core.lsp"
require "config.options"
require "config.keymaps"
require "config.autocmds"
require "config.mason_verify"
require "config.health_check"
require "core.lazy"
